Repository vemser/vemser-vs13-projeto-tshirt-ecomerce-back, pull requests merged in 2024-03, with the labels that each got.

#1 add: classe usuario e DTOs
  src/main/java/br/com/dbc/vemser/iShirts/dto/pessoa/PessoaDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/usuario/UsuarioCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/usuario/UsuarioDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/usuario/UsuarioUpdateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Usuario.java
Labels: enhancement

#7 Feat/endereco
  src/main/java/br/com/dbc/vemser/iShirts/dto/endereco/EnderecoCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/endereco/EnderecoDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Endereco.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Pessoa.java
Labels: enhancement

#8 add: crud de usuario
  src/main/java/br/com/dbc/vemser/iShirts/controller/UsuarioController.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/usuario/UsuarioCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/usuario/UsuarioDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/usuario/UsuarioUpdateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/exceptions/CustomGlobalExceptionHandler.java
  src/main/java/br/com/dbc/vemser/iShirts/exceptions/RegraDeNegocioException.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Usuario.java
  src/main/java/br/com/dbc/vemser/iShirts/model/enums/Ativo.java
  src/main/java/br/com/dbc/vemser/iShirts/repository/UsuarioRepository.java
  src/main/java/br/com/dbc/vemser/iShirts/service/UsuarioService.java
Labels: enhancement

#9 Feat/endereco
  src/main/java/br/com/dbc/vemser/iShirts/dto/pessoa/PessoaCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Endereco.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Pessoa.java
  src/main/java/br/com/dbc/vemser/iShirts/service/PessoaService.java
Labels: enhancement

#15 test: usuario service
  src/main/java/br/com/dbc/vemser/iShirts/controller/UsuarioController.java
  src/main/java/br/com/dbc/vemser/iShirts/service/UsuarioService.java
  src/test/java/br/com/dbc/vemser/iShirts/service/UsuarioServiceTest.java
  src/test/java/br/com/dbc/vemser/iShirts/service/mocks/MockUsuario.java
Labels: tests

#17 add: interface e fix em service
  src/main/java/br/com/dbc/vemser/iShirts/controller/FotoController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/PessoaController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/ProdutoController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/UsuarioController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/interfaces/PessoaControllerInterface.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/interfaces/UsuarioControllerInterface.java
  src/main/java/br/com/dbc/vemser/iShirts/service/UsuarioService.java
Labels: documentation

#16 Feat/autenticacao
  pom.xml
  src/main/java/br/com/dbc/vemser/iShirts/controller/AuthController.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/auth/AlteraSenhaDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/auth/LoginDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/repository/UsuarioRepository.java
  src/main/java/br/com/dbc/vemser/iShirts/security/AuthenticationService.java
  src/main/java/br/com/dbc/vemser/iShirts/security/SecurityConfiguration.java
  src/main/java/br/com/dbc/vemser/iShirts/security/TokenAuthenticationFilter.java
  src/main/java/br/com/dbc/vemser/iShirts/security/TokenService.java
  src/main/java/br/com/dbc/vemser/iShirts/service/UsuarioService.java
  src/main/resources/application.properties
Labels: WorkInProgress

#20 Feat/crud endereco
  src/main/java/br/com/dbc/vemser/iShirts/controller/EnderecoController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/interfaces/EnderecoControllerInterface.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/endereco/EnderecoCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/endereco/EnderecoDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/repository/EnderecoRepository.java
  src/main/java/br/com/dbc/vemser/iShirts/service/EnderecoService.java
Labels: enhancement

#25 fix: endpoints, DTOs e interfaces
  src/main/java/br/com/dbc/vemser/iShirts/controller/AuthController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/CargoController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/UsuarioController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/interfaces/EnderecoControllerInterface.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/interfaces/UsuarioControllerInterface.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/auth/AlteraSenhaDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/auth/LoginDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/usuario/ClienteCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/usuario/UsuarioDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/repository/CargoRepository.java
  src/main/java/br/com/dbc/vemser/iShirts/security/SecurityConfiguration.java
  src/main/java/br/com/dbc/vemser/iShirts/service/CargoService.java
  src/main/java/br/com/dbc/vemser/iShirts/service/UsuarioService.java
Labels: documentation

#30 Testes para os métodos do cargoService
  src/test/java/br/com/dbc/vemser/iShirts/service/CargoServiceTest.java
Labels: tests

#33 Fix/endereco
  src/main/java/br/com/dbc/vemser/iShirts/controller/EnderecoController.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/endereco/EnderecoCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/endereco/EnderecoDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/produto/ProdutoDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Endereco.java
  src/main/java/br/com/dbc/vemser/iShirts/service/EnderecoService.java
Labels: bug

#36 Feat/item pedido
  src/main/java/br/com/dbc/vemser/iShirts/controller/CarrinhoController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/interfaces/CarrinhoControllerInterface.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/carrinho/CarrinhoCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/carrinho/CarrinhoDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/item/ItemCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/item/ItemDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/item/ItemUpdateQuantidadeDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Carrinho.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Item.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Pedido.java
  src/main/java/br/com/dbc/vemser/iShirts/model/enums/MetodoPagamento.java
  src/main/java/br/com/dbc/vemser/iShirts/model/enums/StatusPedido.java
  src/main/java/br/com/dbc/vemser/iShirts/repository/CarrinhoRepository.java
  src/main/java/br/com/dbc/vemser/iShirts/repository/ItemRepository.java
  src/main/java/br/com/dbc/vemser/iShirts/service/CarrinhoService.java
  src/main/java/br/com/dbc/vemser/iShirts/service/ItemService.java
  src/main/java/br/com/dbc/vemser/iShirts/service/UsuarioService.java
  src/test/java/br/com/dbc/vemser/iShirts/service/CarrinhoServiceTest.java
  src/test/java/br/com/dbc/vemser/iShirts/service/ItemServiceTest.java
  src/test/java/br/com/dbc/vemser/iShirts/service/mocks/MockCarrinho.java
  src/test/java/br/com/dbc/vemser/iShirts/service/mocks/MockFoto.java
  src/test/java/br/com/dbc/vemser/iShirts/service/mocks/MockItem.java
  src/test/java/br/com/dbc/vemser/iShirts/service/mocks/MockProduto.java
  src/test/java/br/com/dbc/vemser/iShirts/service/mocks/MockVariacao.java
Labels: documentation, enhancement, tests

#38 feat/cupom
  src/main/java/br/com/dbc/vemser/iShirts/controller/CupomController.java
  src/main/java/br/com/dbc/vemser/iShirts/controller/interfaces/CupomControllerInterface.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/cupom/CupomCreateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/cupom/CupomDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/dto/cupom/CupomUpdateDTO.java
  src/main/java/br/com/dbc/vemser/iShirts/model/Cupom.java
  src/main/java/br/com/dbc/vemser/iShirts/repository/CupomRepository.java
  src/main/java/br/com/dbc/vemser/iShirts/service/CupomService.java
  src/test/java/br/com/dbc/vemser/iShirts/service/CupomServiceTest.java
  src/test/java/br/com/dbc/vemser/iShirts/service/mocks/MockCupom.java
Labels: enhancement

#39 tests: produto service
  src/main/java/br/com/dbc/vemser/iShirts/service/ProdutoService.java
  src/test/java/br/com/dbc/vemser/iShirts/service/ProdutoServiceTest.java
  src/test/java/br/com/dbc/vemser/iShirts/service/mocks/MockProduto.java
Labels: tests
